---
# tasks file for set_hostname

- name: Set the current MAC address for primary network interface.
  set_fact:
    server_mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"

- name: Set Hostname based on MAC address.
  set_fact:
    server_hostname: "{{ mac_address_mapping[server_mac_address].name }}"

- name: Setup required files.
  template:
    src: "templates/etc/{{ item.template }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { template: "hostname-{{ ansible_os_family }}.j2", dest: /etc/hostname }
    - { template: hosts.j2, dest: /etc/hosts }
  notify:
    - Update hostname on {{ ansible_os_family }} based servers
